create_company_link: '/firms/new'
create_product_link: '/buy/new'
catalog: '/offers'
catalog_p: '/products/'

rubric: 'Летние платья'

unlogin_link:
  type: :xpath
  locator: "//a[text()='Выход']"

create_company:
  name:
    type: :id
    locator: 'company_name'
  type:
    type: :id
    locator: 'search-str'
  code:
    type: :id
    locator: 'address_phones_attributes_0_code'
  number:
    type: :id
    locator: 'address_phones_attributes_0_number'
  submit:
    type: :name
    locator: 'commit'
create_product:
  name:
    type: :id
    locator: 'product_name'
  rubric_search:
    type: :css
    locator: '.js-input-rubric-search'
  rubric_search_submit:
    type: :css
    locator: '.js-button-rubric-search'
  rubric:
    type: :xpath
    locator: "//a[text()='Летние платья']"
  submit:
    type: :name
    locator: 'commit'
page_creator_submit_button:
  type: :name
  locator: 'commit'
